const products = [
  { id: 'royal', name: 'Royal Delicious', note: 'Deep red with natural golden stripes', price: 220, harvest: 'August–September', stock: 'Available now', limited: false, image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?auto=format&fit=crop&w=900&q=85' },
  { id: 'golden', name: 'Golden Delicious', note: 'Golden-yellow skin with gentle honey notes', price: 210, harvest: 'September–October', stock: 'Available now', limited: false, image: 'https://img.imageboss.me/fourwinds/width/425/dpr:2/shop/files/Golden-Delicious-Apple-Tree.jpg?v=1696282589' },
  { id: 'kashmiri', name: 'Kashmiri Red', note: 'Juicy, tart & mountain-grown', price: 250, harvest: 'September–October', stock: 'Limited stock', limited: true, image: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?auto=format&fit=crop&w=900&q=85' },
  { id: 'red-chief', name: 'Red Chief', note: 'Bold ruby-red skin with a clean crunch', price: 230, harvest: 'August–September', stock: 'Available now', limited: false, image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=900&q=85' },
  { id: 'gala', name: 'Gala', note: 'Aromatic, mellow and naturally sweet', price: 240, harvest: 'August–September', stock: 'Limited stock', limited: true, image: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?auto=format&fit=crop&w=900&q=85' },
  { id: 'granny-smith', name: 'Granny Smith', note: 'Bright green, sharp and refreshing', price: 200, harvest: 'September–October', stock: 'Available now', limited: false, image: 'https://images.unsplash.com/photo-1695547817244-43da632d81fd?auto=format&fit=crop&w=900&q=85' },
  { id: 'scarlet-spur', name: 'Scarlet Spur', note: 'Dense, sweet flesh and a ruby finish', price: 280, harvest: 'September–October', stock: 'Limited stock', limited: true, image: 'https://images.unsplash.com/photo-1727120279660-5c28b8461609?auto=format&fit=crop&w=900&q=85' }
];
const hindiLabels = {
  basket: 'टोकरी',
  shop: 'सेब खरीदें',
  tours: 'फार्म भ्रमण',
  story: 'हमारी कहानी',
  contact: 'संपर्क करें',
  available: 'अभी उपलब्ध',
  limited: 'सीमित स्टॉक',
  add: 'टोकरी में जोड़ें',
  delivery: 'सावधानी से डिलीवरी',
  areas: 'डिलीवरी क्षेत्र',
  minimum: 'न्यूनतम ऑर्डर',
  packing: 'पैकिंग',
  timing: 'अनुमानित डिलीवरी'
};
let hindiEnabled = localStorage.getItem('orchard-language') === 'hi';

let cart = (() => {
  try {
    const savedCart = JSON.parse(localStorage.getItem('orchard-cart') || '[]');
    return Array.isArray(savedCart)
      ? savedCart.filter((item) => products.some((product) => product.id === item.id) && Number.isInteger(item.quantity) && item.quantity > 0)
      : [];
  } catch {
    return [];
  }
})();
const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
const cartCount = () => cart.reduce((total, item) => total + item.quantity, 0);
const saveCart = () => localStorage.setItem('orchard-cart', JSON.stringify(cart));

function shell() {
  document.querySelector('#root').innerHTML = `
    <header class="site-header">
      <a class="brand" href="#top" aria-label="Bhardwaj's Orchard home"><span>✦</span> Bhardwaj's <em>Orchard</em></a>
      <nav aria-label="Primary navigation"><a href="#apples">Shop apples</a><a href="#experience">Farm tours</a><a href="#story">Our story</a><a href="#contact">Contact</a></nav>
      <button class="basket" id="open-cart" aria-label="Open basket">⌑ Basket <b id="cart-count">${cartCount()}</b></button>
    </header>
    <main id="top">
      <section class="hero">
        <div class="hero-copy"><p class="eyebrow">⌁ Grown high in the hills</p><h1>Good apples.<br><em>Good days.</em></h1><p class="lead">Hand-picked fruit and unhurried farm moments from our family orchard in the Himalayas.</p><div class="actions"><a href="#apples" class="button">Explore the harvest <span>→</span></a><a class="text-link" href="#experience">Plan a farm visit →</a></div></div>
        <div class="hero-image"><img src="https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=1400&q=90" alt="Fresh red apple growing on an orchard tree"/><div class="image-label"><b>01</b><span>From our trees<br>to your table</span></div></div>
      </section>
      <section class="harvest" id="apples"><div class="section-title"><p class="eyebrow">This season's pick</p><h2>Fresh from the orchard</h2><p>Thoughtfully packed, naturally delicious apples delivered with care. Choose your quantity and send us an order enquiry on WhatsApp.</p></div><div class="product-grid">${products.map(productCard).join('')}</div></section>
      <section class="story" id="story"><div class="story-photo"><img src="https://hpgeneralstudies.com/wp-content/uploads/2020/07/Apple-Orchards-Shimla-Himachal-Pradesh-HP-Shiva-Project.jpg" alt="Apple harvest in a Himachal Pradesh orchard" loading="lazy"/></div><div class="story-copy"><p class="eyebrow">About Bhardwaj's Orchard</p><h2>Rooted in Balson. Grown with patience.</h2><p>Bhardwaj's Orchard sits in Behlawag Deha, Balson, in the apple-growing hills of Shimla, Himachal Pradesh. This is a place shaped by cool mountain air, sloping land and seasons that move at their own pace. From winter pruning and spring blossom to the busy weeks of harvest, our family works closely with the land throughout the year.</p><p>We believe fruit should be grown carefully, picked honestly and shared while it is at its best. Every apple is checked by hand for colour, firmness and natural maturity before it is packed. Whether you order a small box, plan a visit or enquire about wholesale fruit, you are dealing directly with the orchard family in Balson.</p><ul><li>Hand-selected at peak ripeness</li><li>Carefully packed for freshness</li><li>Seasonal fruit, direct from grower</li><li>Family-led service from Balson, Shimla</li></ul><a href="#contact" class="text-link">Talk to the orchard →</a></div></section>
      <section class="experience" id="experience"><div class="experience-copy"><p class="eyebrow">Visit the orchard</p><h2>Come closer to the harvest.</h2><p>Spend an unhurried day among the trees. During the season, visitors can walk the rows with our family, see how we choose fruit at peak ripeness, and enjoy the clear mountain air that gives Himalayan apples their character.</p><p>Farm visits are ideal for families, small groups, schools and anyone curious about where real fruit begins. We will help you plan a relaxed visit around the weather and orchard work, with plenty of time for photographs, questions and fresh apples.</p><div class="visit-details"><span><b>Best time</b>August–October</span><span><b>Visit style</b>By prior booking</span><span><b>What to bring</b>Comfortable shoes</span></div><a href="#contact" class="button light">Book a farm visit <span>→</span></a></div><div class="farm-gallery"><img class="farm-photo tall" src="https://images.tribuneindia.com/cms/gall_content/2016/8/2016_8%24largeimg07_Sunday_2016_225844777.jpg" alt="Apple grower harvesting fruit in Himachal Pradesh" loading="lazy"/><img class="farm-photo" src="https://media.fortuneindia.com/fortune-india/2025-04-09/sgqhztvl/Apple_Photo_Feature_3.JPG" alt="Terraced apple orchard in Himachal Pradesh" loading="lazy"/><img class="farm-photo" src="https://hpgeneralstudies.com/wp-content/uploads/2020/07/Apple-Orchards-Shimla-Himachal-Pradesh-HP-Shiva-Project.jpg" alt="Apple picking in a Shimla orchard" loading="lazy"/></div></section>
      <section class="delivery" aria-labelledby="delivery-title"><div><p class="eyebrow">Delivered with care</p><h2 id="delivery-title">From Balson to your doorstep.</h2></div><div class="delivery-grid"><article><b>Delivery areas</b><p>Shimla and nearby Himachal Pradesh locations. Contact us for other destinations.</p></article><article><b>Minimum order</b><p>Orders start from 5 kg so your fruit travels safely and arrives fresh.</p></article><article><b>Packing</b><p>Each order is hand-checked, cushioned and packed in sturdy orchard boxes.</p></article><article><b>Estimated delivery</b><p>Usually 1–3 days locally after confirmation; longer for distant deliveries.</p></article></div></section>
      <section class="contact" id="contact"><div class="contact-copy"><p class="eyebrow">Let's talk apples</p><h2>We would love to hear from you.</h2><p>For orders, farm visits, wholesale, or a simple question—send us a message and Ankush will get back to you.</p><a href="mailto:ankushworks09@gmail.com">ankushworks09@gmail.com</a><a href="tel:+918278867579">+91 82788 67579</a><div class="location"><p class="eyebrow">Find us on</p><h3>Behlawag Deha, Balson</h3><p>Shimla, Himachal Pradesh</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Behlawag%20Deha%20Balson%20Shimla%20Himachal%20Pradesh" target="_blank" rel="noreferrer">Open in Google Maps →</a></div><p class="owner">Ankush Bhardwaj<br><span>Bhardwaj's Orchard</span></p></div><form id="contact-form" novalidate><label>Name<input name="name" required minlength="2" autocomplete="name" placeholder="Your name"/></label><label>Email<input name="email" required type="email" autocomplete="email" placeholder="you@example.com"/></label><label>Phone number<input name="phone" required type="tel" autocomplete="tel" placeholder="Your phone number"/></label><label>I'm interested in<select name="interest"><option>Buying apples</option><option>Farm visit</option><option>Wholesale order</option><option>General enquiry</option></select></label><label class="wide">Message<textarea name="message" required minlength="10" placeholder="How can we help?"></textarea></label><button class="button wide" type="submit">Send message <span>→</span></button><p class="form-note" id="form-note" aria-live="polite"></p></form></section>
    </main>
    <footer><span>© ${new Date().getFullYear()} Bhardwaj's Orchard</span><span>Grown with care in Balson, Shimla</span><a href="#top">Back to top ↑</a></footer>
    <aside class="cart-panel" id="cart-panel" aria-hidden="true"><div class="cart-head"><h2>Your basket</h2><button id="close-cart" aria-label="Close basket">×</button></div><div id="cart-items"></div><div class="cart-total"><span>Estimated total</span><strong id="cart-total">${money(0)}</strong></div><a class="button checkout" href="https://wa.me/918278867579" id="checkout">Order on WhatsApp <span>→</span></a><p class="cart-note">Final availability and delivery charges are confirmed on WhatsApp.</p></aside><div class="overlay" id="overlay"></div>`;
  bind(); renderCart();
}
function productCard(product) { return `<article class="product ${product.id}"><div class="product-image"><img src="${product.image}" alt="${product.name} apples" loading="lazy"/><span class="stock ${product.limited ? 'limited' : ''}">${product.stock}</span></div><div><p>${product.note}</p><h3>${product.name}</h3><span class="harvest-month">Harvest: ${product.harvest}</span><div class="product-bottom"><strong>${money(product.price)} <small>/ kg</small></strong><div class="quantity-picker" aria-label="Choose quantity for ${product.name}">${[1, 2, 5, 10].map((quantity) => `<button type="button" class="quantity ${quantity === 1 ? 'selected' : ''}" data-quantity="${quantity}">${quantity} kg</button>`).join('')}</div><button class="add" data-id="${product.id}">Add to basket</button></div></div></article>`; }
function bind() {
  insertExperiences();
  const languageToggle = document.createElement('button');
  languageToggle.type = 'button';
  languageToggle.className = 'language-toggle';
  languageToggle.textContent = hindiEnabled ? 'English' : 'हिंदी';
  languageToggle.addEventListener('click', toggleHindi);
  document.querySelector('.site-header').append(languageToggle);
  document.querySelectorAll('.quantity').forEach((button) => button.addEventListener('click', () => { const picker = button.closest('.quantity-picker'); picker.querySelectorAll('.quantity').forEach((option) => option.classList.remove('selected')); button.classList.add('selected'); }));
  document.querySelectorAll('.add').forEach((button) => button.addEventListener('click', () => add(button.dataset.id, Number(button.closest('.product').querySelector('.quantity.selected').dataset.quantity))));
  document.querySelector('#open-cart').addEventListener('click', openCart);
  document.querySelector('#close-cart').addEventListener('click', closeCart);
  document.querySelector('#overlay').addEventListener('click', closeCart);
  document.querySelector('#checkout').addEventListener('click', checkoutWhatsApp);
  document.querySelector('#contact-form').addEventListener('submit', sendContact);
  if (hindiEnabled) applyLanguage();
}
function insertExperiences() { const contact = document.querySelector('#contact'); contact.insertAdjacentHTML('beforebegin', `<section class="farm-experiences" aria-labelledby="experiences-title"><div class="section-title"><p class="eyebrow">Spend a day with us</p><h2 id="experiences-title">Orchard experiences</h2><p>Slow down, walk the rows and discover the work behind every apple from Bhardwaj's Orchard in Balson.</p></div><div class="experience-cards"><article class="experience-card"><img src="https://hpgeneralstudies.com/wp-content/uploads/2020/07/Apple-Orchards-Shimla-Himachal-Pradesh-HP-Shiva-Project.jpg" alt="Apple orchard walk in Himachal Pradesh" loading="lazy"/><div><div class="experience-meta"><span>90 minutes</span><b>₹350 / guest</b></div><h3>The Orchard Walk</h3><p>Wander through our Balson orchard with the grower, learn about the trees and taste the day's fresh picks.</p><ul><li>Guided hillside walk</li><li>Seasonal apple tasting</li><li>Tea and orchard stories</li></ul><a href="#contact" class="experience-link">Book this experience <span>→</span></a></div></article><article class="experience-card"><img src="https://images.tribuneindia.com/cms/gall_content/2016/8/2016_8%24largeimg07_Sunday_2016_225844777.jpg" alt="Apple harvesting in Himachal Pradesh" loading="lazy"/><div><div class="experience-meta"><span>3 hours</span><b>₹750 / guest</b></div><h3>Harvest Day Experience</h3><p>Join the harvest in season, fill your own basket and enjoy a simple orchard-style meal among the trees.</p><ul><li>Pick your own basket</li><li>Farm-style lunch</li><li>Take-home tasting box</li></ul><a href="#contact" class="experience-link">Book this experience <span>→</span></a></div></article><article class="experience-card"><img src="https://media.fortuneindia.com/fortune-india/2025-04-09/sgqhztvl/Apple_Photo_Feature_3.JPG" alt="Himachal Pradesh apple orchard at harvest" loading="lazy"/><div><div class="experience-meta"><span>2 hours</span><b>₹550 / guest</b></div><h3>Sunset Tasting Table</h3><p>Settle into the orchard as evening arrives for a gentle apple tasting with local flavours and mountain views.</p><ul><li>Curated apple flight</li><li>Local cheese pairing</li><li>Golden-hour views</li></ul><a href="#contact" class="experience-link">Book this experience <span>→</span></a></div></article></div></section>`); }
function toggleHindi() { hindiEnabled = !hindiEnabled; localStorage.setItem('orchard-language', hindiEnabled ? 'hi' : 'en'); document.documentElement.lang = hindiEnabled ? 'hi' : 'en'; applyLanguage(); }
function applyLanguage() { const copy = hindiEnabled ? hindiLabels : null; const nav = document.querySelector('nav'); const navLabels = copy ? [copy.shop, copy.tours, copy.story, copy.contact] : ['Shop apples', 'Farm tours', 'Our story', 'Contact']; nav.querySelectorAll('a').forEach((link, index) => { link.textContent = navLabels[index]; }); document.querySelector('.basket').childNodes[2].textContent = ` ${copy ? copy.basket : 'Basket'} `; document.querySelectorAll('.stock').forEach((badge) => { badge.textContent = badge.classList.contains('limited') ? (copy ? copy.limited : 'Limited stock') : (copy ? copy.available : 'Available now'); }); document.querySelectorAll('.add').forEach((button) => { button.textContent = copy ? copy.add : 'Add to basket'; }); const deliveryLabels = copy ? [copy.delivery, copy.areas, copy.minimum, copy.packing, copy.timing] : ['Delivered with care', 'Delivery areas', 'Minimum order', 'Packing', 'Estimated delivery']; const eyebrow = document.querySelector('.delivery .eyebrow'); eyebrow.textContent = deliveryLabels[0]; document.querySelectorAll('.delivery-grid b').forEach((heading, index) => { heading.textContent = deliveryLabels[index + 1]; }); const toggle = document.querySelector('.language-toggle'); toggle.textContent = hindiEnabled ? 'English' : 'हिंदी'; }
function add(id, quantity) { const found = cart.find((item) => item.id === id); if (found) found.quantity += quantity; else cart.push({ id, quantity }); saveCart(); renderCart(); openCart(); }
function remove(id) { cart = cart.filter((item) => item.id !== id); saveCart(); renderCart(); }
function renderCart() { document.querySelector('#cart-count').textContent = cartCount(); const host = document.querySelector('#cart-items'); host.innerHTML = cart.length ? cart.map((item) => { const p = products.find((product) => product.id === item.id); return `<div class="cart-item"><img src="${p.image}" alt=""/><div><b>${p.name}</b><span>${item.quantity} kg · ${money(p.price * item.quantity)}</span></div><button class="remove" data-id="${item.id}" aria-label="Remove ${p.name}">×</button></div>`; }).join('') : '<p class="empty">Your basket is waiting for something delicious.</p>'; document.querySelector('#cart-total').textContent = money(cart.reduce((total, item) => total + products.find((p) => p.id === item.id).price * item.quantity, 0)); document.querySelectorAll('.remove').forEach((button) => button.addEventListener('click', () => remove(button.dataset.id))); }
function openCart() { document.querySelector('#cart-panel').classList.add('visible'); document.querySelector('#overlay').classList.add('visible'); document.querySelector('#cart-panel').setAttribute('aria-hidden', 'false'); }
function closeCart() { document.querySelector('#cart-panel').classList.remove('visible'); document.querySelector('#overlay').classList.remove('visible'); document.querySelector('#cart-panel').setAttribute('aria-hidden', 'true'); }
function checkoutWhatsApp(event) { event.preventDefault(); if (!cart.length) return; const items = cart.map((item) => { const product = products.find((candidate) => candidate.id === item.id); return `• ${product.name}: ${item.quantity} kg — ${money(product.price * item.quantity)}`; }).join('\n'); const total = cart.reduce((sum, item) => sum + products.find((product) => product.id === item.id).price * item.quantity, 0); const message = `Hello Bhardwaj's Orchard!%0A%0AI would like to enquire about this order:%0A${encodeURIComponent(items)}%0A%0AEstimated total: ${encodeURIComponent(money(total))}%0A%0APlease confirm availability, delivery area and final charges.`; window.open(`https://wa.me/918278867579?text=${message}`, '_blank', 'noopener'); closeCart(); }
async function sendContact(event) { event.preventDefault(); const form = event.currentTarget; const note = document.querySelector('#form-note'); const button = form.querySelector('[type="submit"]'); if (!form.checkValidity()) { form.reportValidity(); return; } button.disabled = true; button.textContent = 'Sending…'; note.textContent = ''; try { const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const isJson = response.headers.get('content-type')?.includes('application/json'); const result = isJson ? await response.json() : {}; if (!response.ok) throw new Error(result.error || 'Unable to send your message right now. Please call us instead.'); note.textContent = result.message; note.className = 'form-note success'; form.reset(); } catch (error) { note.textContent = error.message || 'Something went wrong. Please call us instead.'; note.className = 'form-note error'; } finally { button.disabled = false; button.innerHTML = 'Send message <span>→</span>'; } }
shell();
